default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  username: postgres
  password: postgres

development:
  <<: *default
  database: exp_book_development

test:
  <<: *default
  database: exp_book_test

production:
  <<: *default
  database: exp_book_production
