default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: catawiki_development

test:
  <<: *default
  database: catawiki_test

production:
  <<: *default
  database: catawiki_production
