default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: know_development

test:
  <<: *default
  database: know_test

production:
  <<: *default
  database: know_production
